public enum StatusType
{
    Strength,
    Vuln,
    Weakness,
    Regen,
    Dexterity,
    Poison,
    Awakening,
    FullMoon,
    Slow,
    Haste,
    Divination,
    Targeting,
    Jump,
    Fragile,
    Speed,
    Accelerate,
    Stun,
    Strengthen,
    Clock,
    After,
    Burn,
    Sadism,
    Brand,
    MechaArm,
    Energy,
    Continuous,
    Crystallize,
    LifeCycle,
    RiskManagement,
    Trap,
    Elastic,
    Shielding,
    Plating,
    DelayImmunity,
    ArmorBlock,
    Thorns,
    FullBreak,
    Status,
    CostNullify,
    CardFollowUp,
    Echo,
    FieldTurnFollowUp,
    Vigor,
    Artifact,
    Filter,
    DelayedStun,
    DebuffHalt,
    Freeze,
    DelayedDeath,
    AreaDmgReduction,
    ConserveArmor,
    EnergyUp,
    Vulnerabilize,
    Imitate,
    FullThrottle,
    Fatigue,
    DamageReduction,
    AnyCardFollowUp,
    Regulator,
    Blind,
    Link,
    Hide,
    Undead,
    Sap,
    TimeStop,
    Signal,
    Unbiased,
    Production,
    FullMoonTemp,

    // Ajoutés en dernier : cet enum est sérialisé par index dans les ScriptableObjects, donc
    // insérer ailleurs réécrirait silencieusement le statut de toutes les cartes suivantes.
    Adaptation,
    Fervor,
    Confusion,
    Overpower,
    Steadfast,
    DispelBlock,
    Smoke,
    Absorption,
    TimeCompression,
    Rage,

    // Gardés à la fin : les ScriptableObjects sérialisent cette valeur par index.
    Momentum,
    Charge,
    Exposure,
    Fortify,
    Instability,
    Precision,
    PowerPassive,
    Infaillible,

    // Gardés à la fin : les ScriptableObjects sérialisent cette valeur par index.
    Univers,
    Megacristal,
    Fragmentation,
    Propulsion,
    Empathie,
    Avenir,
    Innocence,
    MesuresEnvergure,

    // Gardés à la fin : les ScriptableObjects sérialisent cette valeur par index.
    LamesArdentes,
    Sublimation,
    AmeArtiste,
    GrandeOeuvre,
    ParcNaturel,
    Pavillon,
    SuiteArithmetique,
    MurOffensif,
    SeptiemeVitesse,
    FreinMoteur,
    Galvanisation,
    Tenebres,

    // Gardés à la fin : les ScriptableObjects sérialisent cette valeur par index.
    Provocation,
    Adrenaline,
    Miracle,
    Analyse,
    Compilation,
    Chaotic,

    // Gardés à la fin : les ScriptableObjects sérialisent cette valeur par index. Ces deux
    // stades ne se posent jamais depuis une carte ; le serveur les fait naître de Sadism et
    // les envoie sous ces noms, que le client doit connaître pour les afficher.
    SadismII,
    SadismIII,

    // Ajoutés en dernier, pour la même raison : l'index est ce qui est sérialisé.
    Astra,
    Sol,
    Luna,
    Critical,
    TimeDistortion
}